/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JComponent;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import Interfaz.Login;

/**
 *
 * @author jhess
 */
public class Time extends javax.swing.JInternalFrame {
   private final JComponent northPane;
   private Border border;
   
   private Timer fecha;
    private int sec, min, hrs,fech;
    
    private ActionListener acciones = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            sec++;
           if(sec==60){
               min++;
               sec=0;
           }
           if(min==60){
               hrs++;
               min=0;
           }
            Refreshtime();
        }
    };
    
    private void Refreshtime(){
        Date d = new Date();
        SimpleDateFormat fechf = new SimpleDateFormat("yyyy-MM-dd ");

        FeYHo.setText(fechf.format(d)+(hrs<=9?"0":"")+hrs+":"+(min<=9?"0":"")+min+":"+(sec<=9?"0":"")+sec);
    }
   
    /**
     * Creates new form Time
     */
    public Time() {
        initComponents();
        this.setEnabled(false);
         northPane = ((BasicInternalFrameUI) getUI()).getNorthPane();
         border = getBorder();
         this.setUndecorated(true);
        Date d = new Date();
        SimpleDateFormat secf = new SimpleDateFormat("ss");
        SimpleDateFormat minf = new SimpleDateFormat("mm");
        SimpleDateFormat hrsf = new SimpleDateFormat("HH");

        sec= Integer.parseInt(secf.format(d));
        min= Integer.parseInt(minf.format(d));
        hrs= Integer.parseInt(hrsf.format(d));

        fecha = new Timer(1000,acciones);
        fecha.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FeYHo = new javax.swing.JLabel();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Fecha");
        setToolTipText("");
        setEnabled(false);
        setFocusCycleRoot(false);
        setFocusTraversalPolicyProvider(true);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(260, 70));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FeYHo.setFont(new java.awt.Font("Calisto MT", 3, 24)); // NOI18N
        FeYHo.setForeground(new java.awt.Color(0, 102, 0));
        FeYHo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FeYHo.setOpaque(true);
        getContentPane().add(FeYHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    public void setRootPaneCheckingEnabled(boolean enabled)
    {
        super.setRootPaneCheckingEnabled(enabled);
    }
    
    public void setUndecorated(boolean val)
{
    setBorder(val ? null : border);

    setRootPaneCheckingEnabled(false);
    ((BasicInternalFrameUI) getUI()).setNorthPane(val ? null : northPane);
    setRootPaneCheckingEnabled(true);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel FeYHo;
    // End of variables declaration//GEN-END:variables
}
